parameters:
  jenkins:
    client:
      job:
        docker-build-images-docker-ci-tempest:
          name: docker-build-images-docker-ci-tempest
          discard:
            build:
              keep_num: 30
            artifact:
              keep_num: 30
          type: workflow-scm
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/oss/jenkins/pipelines"
            credentials: "gerrit"
            script: docker-build-image-pipeline.groovy
          trigger:
            gerrit:
              project:
                "mcp/docker-ci-tempest":
                  branches:
                    - master
                    - queens
                    - pike
                    - ocata
                    - newton
                    - mitaka
              event:
                patchset:
                  - created:
                      excludeDrafts: false
                      excludeNoCodeChange: false
                change:
                  - merged
                comment:
                  - addedContains:
                      commentAddedCommentContains: 'rebuild'
          param:
            IMAGE_NAME:
              type: string
              default: "ci-tempest"
            IMAGE_TAGS:
              type: string
              default: ""
            CREDENTIALS_ID:
              type: string
              default: "gerrit"
            DOCKER_REGISTRY:
              type: string
              default: "docker-dev-virtual.docker.mirantis.net"
            PROJECT_NAMESPACE:
              type: string
              default: "cicd"
            DOCKERFILE_PATH:
              type: string
              default: "Dockerfile"
            CONTEXT_PATH:
              type: string
              default: "."
